// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2DcGJlf7m5CP5JJRxrfCOd_Zd1mlM8t0',
    appId: '1:701476466181:web:3806211616eba73a1b366c',
    messagingSenderId: '701476466181',
    projectId: 'kazarman-jarnama-62fe1',
    authDomain: 'kazarman-jarnama-62fe1.firebaseapp.com',
    storageBucket: 'kazarman-jarnama-62fe1.appspot.com',
    measurementId: 'G-YWLL0ZN2DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZrvFOHiglBNTz0TcWEHarSId5bLBdFM',
    appId: '1:701476466181:android:82aae8a6b86890261b366c',
    messagingSenderId: '701476466181',
    projectId: 'kazarman-jarnama-62fe1',
    storageBucket: 'kazarman-jarnama-62fe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxNjIBlmgTksG8IB4BYroe0ESWgci8oE',
    appId: '1:701476466181:ios:a2aca31f28b128db1b366c',
    messagingSenderId: '701476466181',
    projectId: 'kazarman-jarnama-62fe1',
    storageBucket: 'kazarman-jarnama-62fe1.appspot.com',
    iosClientId: '701476466181-12vkfclkkmel5rgfehk41s60nok274o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kazarmanJarnama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATxNjIBlmgTksG8IB4BYroe0ESWgci8oE',
    appId: '1:701476466181:ios:a2aca31f28b128db1b366c',
    messagingSenderId: '701476466181',
    projectId: 'kazarman-jarnama-62fe1',
    storageBucket: 'kazarman-jarnama-62fe1.appspot.com',
    iosClientId: '701476466181-12vkfclkkmel5rgfehk41s60nok274o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kazarmanJarnama',
  );
}
